#
# Module manifest for module 'PSLocalModule'
#
# Generated by: Hong Li
#
# Generated on: 26/08/2019
#

@{
    RootModule = 'PSLocalModule.psm1'
    ModuleVersion = '1.0.1'
    GUID = '1993f0dd-60b3-432f-bb56-423026762edd'
    Author = 'Hong Li'
    Copyright = '(c) 2019 Hong Li. All rights reserved.'
    Description = 'PSLocalModule provides commands for testing, installing and listing local modules'
    PowerShellVersion = '5.1'

    FunctionsToExport = @('Set-PSCodePath', 'Get-PSCodePath', 'Test-LocalModule', 'Install-LocalModule')
    CmdletsToExport   = @()
    VariablesToExport = '*'
    AliasesToExport   = @('scp', 'gcp', 'tlm', 'inlm')
    
    PrivateData = @{
        PSData = @{
            Tags         = 'PowerShell', 'Module', 'PSEdition_Core', 'PSEdition_Desktop', 'Windows'
            LicenseUri   = 'https://github.com/hongstack/PSLocalModule/blob/master/LICENSE'
            ProjectUri   = 'https://github.com/hongstack/PSLocalModule'
            ReleaseNotes = 'https://github.com/hongstack/PSLocalModule/releases/tag/1.0.1'
        }
    }
}